spring:
  profiles:
    activate:
      on-profile: dev

---
spring:
  profiles:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:patientHubApp-dev
    username: dev-user
    password: dev-password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

#---
#
#spring:
#  profiles:
#    activate:
#      on-profile: qa
#  h2:
#    console:
#      enabled: true
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:patientHubApp-qa
#    username: qa-user
#    password: qa-password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#
#---
#
#spring:
#  profiles:
#    activate:
#      on-profile: prod
#  h2:
#    console:
#      enabled: true
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:patientHubApp-prod
#    username: prod-user
#    password: prod-password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect